package friba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import friba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.11 19:36:45 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KierrosTest {



  // Generated by ComTest BEGIN
  /** testAnna91 */
  @Test
  public void testAnna91() {    // Kierros: 91
    Kierros kier = new Kierros(); 
    kier.parse("   2   |  10  |   Kalastus  | 1949 | 22 t "); 
    assertEquals("From: Kierros line: 94", "2", kier.anna(0)); 
    assertEquals("From: Kierros line: 95", "10", kier.anna(1)); 
    assertEquals("From: Kierros line: 96", "Kalastus", kier.anna(2)); 
    assertEquals("From: Kierros line: 97", "1949", kier.anna(3)); 
    assertEquals("From: Kierros line: 98", "22", kier.anna(4)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta128 */
  @Test
  public void testAseta128() {    // Kierros: 128
    Kierros kier = new Kierros(); 
    assertEquals("From: Kierros line: 130", null, kier.aseta(3,"kissa")); 
    assertEquals("From: Kierros line: 131", null, kier.aseta(3,"1940")); 
    assertEquals("From: Kierros line: 132", null, kier.aseta(4,"20")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone175 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone175() throws CloneNotSupportedException {    // Kierros: 175
    Kierros kier = new Kierros(); 
    kier.parse("   2   |  10  |   Kalastus  | 1949 | 22 t "); 
    Kierros kopio = kier.clone(); 
    assertEquals("From: Kierros line: 180", kier.toString(), kopio.toString()); 
    kier.parse("   1   |  11  |   Uinti  | 1949 | 22 t "); 
    assertEquals("From: Kierros line: 182", false, kopio.toString().equals(kier.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi230 */
  @Test
  public void testRekisteroi230() {    // Kierros: 230
    Pelaaja niklas1 = new Pelaaja(); 
    assertEquals("From: Kierros line: 232", 0, niklas1.getTunnusNro()); 
    niklas1.rekisteroi(); 
    Pelaaja niklas2 = new Pelaaja(); 
    niklas2.rekisteroi(); 
    int n1 = niklas1.getTunnusNro(); 
    int n2 = niklas2.getTunnusNro(); 
    assertEquals("From: Kierros line: 238", n2-1, n1); 
  } // Generated by ComTest END
}