package friba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import friba.*;
// Generated by ComTest END
import kanta.SailoException;

/**
 * Test class made by ComTest
 * @version 2022.05.11 19:50:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajatTest {



  // Generated by ComTest BEGIN
  /** testLisaa45 */
  @Test
  public void testLisaa45() {    // Pelaajat: 45
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja niklas1 = new Pelaaja(), niklas2 = new Pelaaja(); 
    assertEquals("From: Pelaajat line: 48", 0, pelaajat.getLkm()); 
    pelaajat.lisaa(niklas1); assertEquals("From: Pelaajat line: 49", 1, pelaajat.getLkm()); 
    pelaajat.lisaa(niklas2); assertEquals("From: Pelaajat line: 50", 2, pelaajat.getLkm()); 
    pelaajat.lisaa(niklas1); assertEquals("From: Pelaajat line: 51", 3, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 52", niklas1, pelaajat.anna(0)); 
    assertEquals("From: Pelaajat line: 53", niklas2, pelaajat.anna(1)); 
    assertEquals("From: Pelaajat line: 54", niklas1, pelaajat.anna(2)); 
    assertEquals("From: Pelaajat line: 55", false, pelaajat.anna(1) == niklas1); 
    assertEquals("From: Pelaajat line: 56", true, pelaajat.anna(1) == niklas2); 
    pelaajat.lisaa(niklas1); assertEquals("From: Pelaajat line: 57", 4, pelaajat.getLkm()); 
    pelaajat.lisaa(niklas1); assertEquals("From: Pelaajat line: 58", 5, pelaajat.getLkm()); 
    pelaajat.lisaa(niklas1); assertEquals("From: Pelaajat line: 59", 6, pelaajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista119 
   * @throws SailoException when error
   */
  @Test
  public void testPoista119() throws SailoException {    // Pelaajat: 119
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja aku1 = new Pelaaja(), aku2 = new Pelaaja(), aku3 = new Pelaaja(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    pelaajat.lisaa(aku1); pelaajat.lisaa(aku2); pelaajat.lisaa(aku3); 
    assertEquals("From: Pelaajat line: 126", 1, pelaajat.poista(id1+1)); 
    assertEquals("From: Pelaajat line: 127", null, pelaajat.annaId(id1+1)); assertEquals("From: Pelaajat line: 127", 2, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 128", 1, pelaajat.poista(id1)); assertEquals("From: Pelaajat line: 128", 1, pelaajat.getLkm()); 
    assertEquals("From: Pelaajat line: 129", 0, pelaajat.poista(id1+3)); assertEquals("From: Pelaajat line: 129", 1, pelaajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaId284 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaId284() throws SailoException {    // Pelaajat: 284
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja aku1 = new Pelaaja(), aku2 = new Pelaaja(), aku3 = new Pelaaja(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    pelaajat.lisaa(aku1); pelaajat.lisaa(aku2); pelaajat.lisaa(aku3); 
    assertEquals("From: Pelaajat line: 291", true, pelaajat.annaId(id1  ) == aku1); 
    assertEquals("From: Pelaajat line: 292", true, pelaajat.annaId(id1+1) == aku2); 
    assertEquals("From: Pelaajat line: 293", true, pelaajat.annaId(id1+2) == aku3); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsiId308 
   * @throws SailoException when error
   */
  @Test
  public void testEtsiId308() throws SailoException {    // Pelaajat: 308
    Pelaajat pelaajat = new Pelaajat(); 
    Pelaaja aku1 = new Pelaaja(), aku2 = new Pelaaja(), aku3 = new Pelaaja(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    pelaajat.lisaa(aku1); pelaajat.lisaa(aku2); pelaajat.lisaa(aku3); 
    assertEquals("From: Pelaajat line: 315", 1, pelaajat.etsiId(id1+1)); 
    assertEquals("From: Pelaajat line: 316", 2, pelaajat.etsiId(id1+2)); 
  } // Generated by ComTest END
}