package friba.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import friba.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.05.11 19:45:50 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PelaajaTest {



  // Generated by ComTest BEGIN
  /** testAseta123 */
  @Test
  public void testAseta123() {    // Pelaaja: 123
    Pelaaja pelaaja = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 125", null, pelaaja.aseta(1,"Ankka Aku")); 
    assertEquals("From: Pelaaja line: 126", "ÄÄliö", pelaaja.aseta(9,"kissa")); 
    assertEquals("From: Pelaaja line: 127", "ÄÄliö", pelaaja.aseta(9,"1940")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi218 */
  @Test
  public void testRekisteroi218() {    // Pelaaja: 218
    Pelaaja niklas1 = new Pelaaja(); 
    assertEquals("From: Pelaaja line: 220", 0, niklas1.getTunnusNro()); 
    niklas1.rekisteroi(); 
    Pelaaja niklas2 = new Pelaaja(); 
    niklas2.rekisteroi(); 
    int n1 = niklas1.getTunnusNro(); 
    int n2 = niklas2.getTunnusNro(); 
    assertEquals("From: Pelaaja line: 226", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString267 */
  @Test
  public void testToString267() {    // Pelaaja: 267
    Pelaaja pelaaja = new Pelaaja(); 
    pelaaja.parse(" 4  | Vladimir Naapuri   | 39   | Vaasa          |Perus"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals306 */
  @Test
  public void testEquals306() {    // Pelaaja: 306
    Pelaaja pelaaja1 = new Pelaaja(); 
    pelaaja1.parse("   3  |  Ankka Aku   | 030201-111C"); 
    Pelaaja pelaaja2 = new Pelaaja(); 
    pelaaja2.parse("   3  |  Ankka Aku   | 030201-111C"); 
    Pelaaja pelaaja3 = new Pelaaja(); 
    pelaaja3.parse("   3  |  Ankka Aku   | 030201-115H"); 
    assertEquals("From: Pelaaja line: 314", true, pelaaja1.equals(pelaaja2)); 
    assertEquals("From: Pelaaja line: 315", true, pelaaja2.equals(pelaaja1)); 
    assertEquals("From: Pelaaja line: 316", true, pelaaja1.equals(pelaaja3)); 
    assertEquals("From: Pelaaja line: 317", true, pelaaja3.equals(pelaaja2)); 
  } // Generated by ComTest END
}